imgbb:
  IMGBB_UPLOAD_URL: "https://api.imgbb.com/1/upload"
  IMAGE_EXPIRATION: 600 #seconds

model:
  ENCODER_MODEL_PATH: "models/mini_cpm/mmproj-model-f16.gguf"
  DECODER_MODEL_PATH: "models/mini_cpm/ggml-model-Q4_K_M.gguf"
  CONTEXT_LENGHT: 2048
  TEMPERATURE: 0.5

original_model: "transformers_modules/moondream"

logs:
  log_file_path: "logs/graphscribe.log"
  rotation: "1 MB"
  retention: "10 days"


FASTAPI_URL : "http://localhost:8000/describe"
MAX_IMAGE_SIZE: 10485760 # 10 MB


